name: Build and deploy container app to Azure Functions - deploydirectory

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔖 Get release tag name
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true  
          doNotFailIfNotFound : true  
      - name: ♻️ Set correct environment
        run: |
           TAG=${{ steps.get_release.outputs.tag_name }}
           echo "TAG=$TAG" >> "$GITHUB_ENV"
      - name: 🐳 Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/leahlandau/try-${{ matrix.directory }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }}
            type=semver,pattern={{major}},value=${{ env.TAG }} 

      - name: 🏗️ Build and 🫸 push image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/leahlandau/backup:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-functions.outputs.functions-url }}

      steps:
        - name: Deploy to Azure Functions
          id: deploy-to-functions
          uses: azure/functions-deploy@v2
          with:
            app-name: 'deploydirectory'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_aff92f69ba354d7a987ee9d85eb459cc }}
            images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_e4441d2293124e6a95bc5e64676cff9e }}/python:${{ github.sha }}'